### ISSUE TITLE
Has silent fails in github actions with no warnings at all. 

### ISSUE THREAD

**Issue by dobosalparbc** [LuminateOne/eslint-baseline#2]
It supposed to throw an error like this just like native eslint do:
Error: Error while loading rule 'import/no-unused-modules': Cannot find module '**/node_modules/recharts/lib/index'. Please verify that the package.json has a valid "main" entry

But instead I have in the console the following without the github action failing:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.execute (**node_modules/@luminateone/eslint-baseline/src/eslint.js:26:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exec (**node_modules/@luminateone/eslint-baseline/index.js:27:18)

There is an issue with the recharts package, but it wasn't caught

**Comment by JasonEleventeen** [comment]
see https://github.com/LuminateOne/eslint-baseline/pull/4

**Comment by dobosalparbc** [comment]
Thank you!
